//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChinesseCheckersClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChinesseCheckersClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fail to create relation.
        /// </summary>
        public static string Commin_FailToCreateRelation {
            get {
                return ResourceManager.GetString("Commin_FailToCreateRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Common_Accept {
            get {
                return ResourceManager.GetString("Common_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Click)Accept Friend.
        /// </summary>
        public static string Common_AcceptFriend {
            get {
                return ResourceManager.GetString("Common_AcceptFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        public static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change language.
        /// </summary>
        public static string Common_ChangeLanguage {
            get {
                return ResourceManager.GetString("Common_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connextion Down.
        /// </summary>
        public static string Common_ConnectionDown {
            get {
                return ResourceManager.GetString("Common_ConnectionDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection Up.
        /// </summary>
        public static string Common_ConnectionUp {
            get {
                return ResourceManager.GetString("Common_ConnectionUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Match.
        /// </summary>
        public static string Common_CreateMatch {
            get {
                return ResourceManager.GetString("Common_CreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credits.
        /// </summary>
        public static string Common_Credits {
            get {
                return ResourceManager.GetString("Common_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be active.
        /// </summary>
        public static string Common_EmailPolicie {
            get {
                return ResourceManager.GetString("Common_EmailPolicie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string Common_English {
            get {
                return ResourceManager.GetString("Common_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error in database.
        /// </summary>
        public static string Common_ErrorDatabase {
            get {
                return ResourceManager.GetString("Common_ErrorDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Executing.
        /// </summary>
        public static string Common_Executing {
            get {
                return ResourceManager.GetString("Common_Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fail.
        /// </summary>
        public static string Common_Fail {
            get {
                return ResourceManager.GetString("Common_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Free.
        /// </summary>
        public static string Common_Free {
            get {
                return ResourceManager.GetString("Common_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Added.
        /// </summary>
        public static string Common_FriendAdded {
            get {
                return ResourceManager.GetString("Common_FriendAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend List.
        /// </summary>
        public static string Common_FriendList {
            get {
                return ResourceManager.GetString("Common_FriendList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Request Sended to:.
        /// </summary>
        public static string Common_FriendRequestSended {
            get {
                return ResourceManager.GetString("Common_FriendRequestSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Match.
        /// </summary>
        public static string Common_JoinMatch {
            get {
                return ResourceManager.GetString("Common_JoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join sucessfull.
        /// </summary>
        public static string Common_JoinSucessfull {
            get {
                return ResourceManager.GetString("Common_JoinSucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Common_Language {
            get {
                return ResourceManager.GetString("Common_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Launch Match.
        /// </summary>
        public static string Common_LaunchMatch {
            get {
                return ResourceManager.GetString("Common_LaunchMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Common_Login {
            get {
                return ResourceManager.GetString("Common_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximize.
        /// </summary>
        public static string Common_Maximize {
            get {
                return ResourceManager.GetString("Common_Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message to.
        /// </summary>
        public static string Common_MessageTo {
            get {
                return ResourceManager.GetString("Common_MessageTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimize.
        /// </summary>
        public static string Common_Minimize {
            get {
                return ResourceManager.GetString("Common_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        public static string Common_Nickname {
            get {
                return ResourceManager.GetString("Common_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length &lt;= 12.
        /// </summary>
        public static string Common_NicknamePolicie {
            get {
                return ResourceManager.GetString("Common_NicknamePolicie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not color.
        /// </summary>
        public static string Common_NotColor {
            get {
                return ResourceManager.GetString("Common_NotColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not found credentials.
        /// </summary>
        public static string Common_NotFoundCredential {
            get {
                return ResourceManager.GetString("Common_NotFoundCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not found room.
        /// </summary>
        public static string Common_NotFoundRoom {
            get {
                return ResourceManager.GetString("Common_NotFoundRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation Successful.
        /// </summary>
        public static string Common_OperationSuccessful {
            get {
                return ResourceManager.GetString("Common_OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orange.
        /// </summary>
        public static string Common_Orange {
            get {
                return ResourceManager.GetString("Common_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Common_Password {
            get {
                return ResourceManager.GetString("Common_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must contain Upper
        ///Must contain lower
        ///Must contain digits.
        /// </summary>
        public static string Common_PasswordPolicie {
            get {
                return ResourceManager.GetString("Common_PasswordPolicie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player inside.
        /// </summary>
        public static string Common_PlayerInside {
            get {
                return ResourceManager.GetString("Common_PlayerInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players connected:.
        /// </summary>
        public static string Common_PlayersConnected {
            get {
                return ResourceManager.GetString("Common_PlayersConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Policies.
        /// </summary>
        public static string Common_Policies {
            get {
                return ResourceManager.GetString("Common_Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string Common_Profile {
            get {
                return ResourceManager.GetString("Common_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red.
        /// </summary>
        public static string Common_Red {
            get {
                return ResourceManager.GetString("Common_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request not sended.
        /// </summary>
        public static string Common_RequestNotSended {
            get {
                return ResourceManager.GetString("Common_RequestNotSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore.
        /// </summary>
        public static string Common_Restore {
            get {
                return ResourceManager.GetString("Common_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retry.
        /// </summary>
        public static string Common_Retry {
            get {
                return ResourceManager.GetString("Common_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Room full.
        /// </summary>
        public static string Common_RoomFull {
            get {
                return ResourceManager.GetString("Common_RoomFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving.
        /// </summary>
        public static string Common_Saving {
            get {
                return ResourceManager.GetString("Common_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Searching room.
        /// </summary>
        public static string Common_SearchingRoom {
            get {
                return ResourceManager.GetString("Common_SearchingRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Signin.
        /// </summary>
        public static string Common_Signin {
            get {
                return ResourceManager.GetString("Common_Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Common_Spanish {
            get {
                return ResourceManager.GetString("Common_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try.
        /// </summary>
        public static string Common_Try {
            get {
                return ResourceManager.GetString("Common_Try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try to join.
        /// </summary>
        public static string Common_TryToJoin {
            get {
                return ResourceManager.GetString("Common_TryToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turn.
        /// </summary>
        public static string Common_Turn {
            get {
                return ResourceManager.GetString("Common_Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate password.
        /// </summary>
        public static string Common_ValidatePassword {
            get {
                return ResourceManager.GetString("Common_ValidatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Must be the same than password.
        /// </summary>
        public static string Common_ValidatePasswordPolicie {
            get {
                return ResourceManager.GetString("Common_ValidatePasswordPolicie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification Fail.
        /// </summary>
        public static string Common_VerificationFail {
            get {
                return ResourceManager.GetString("Common_VerificationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VolMusic.
        /// </summary>
        public static string Common_VolMusic {
            get {
                return ResourceManager.GetString("Common_VolMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VolSfx.
        /// </summary>
        public static string Common_VolSfx {
            get {
                return ResourceManager.GetString("Common_VolSfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for server reply.
        /// </summary>
        public static string Common_WaitingForServerReply {
            get {
                return ResourceManager.GetString("Common_WaitingForServerReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting user input.
        /// </summary>
        public static string Common_WaitingUserInput {
            get {
                return ResourceManager.GetString("Common_WaitingUserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string Common_Welcome {
            get {
                return ResourceManager.GetString("Common_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a White.
        /// </summary>
        public static string Common_White {
            get {
                return ResourceManager.GetString("Common_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yellow.
        /// </summary>
        public static string Common_Yellow {
            get {
                return ResourceManager.GetString("Common_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your color.
        /// </summary>
        public static string Common_YourColor {
            get {
                return ResourceManager.GetString("Common_YourColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introducce verification code
        /// in your email.
        /// </summary>
        public static string VerificationCodePage_Instructions {
            get {
                return ResourceManager.GetString("VerificationCodePage_Instructions", resourceCulture);
            }
        }
    }
}
